# Generated by Django 4.2.4 on 2023-09-06 09:58

import buttercheecksapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buttercheecksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='address',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='apartment_suite',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='country',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='email',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='order_notes',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='postal_zip',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='state_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_cart',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(max_length=255, null=True, verbose_name=buttercheecksapp.models.UserAddress),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255, null=True, verbose_name=buttercheecksapp.models.UserAddress),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('apartment_suite', models.CharField(blank=True, max_length=100)),
                ('state_country', models.CharField(max_length=100)),
                ('postal_zip', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buttercheecksapp.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buttercheecksapp.size')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buttercheecksapp.size'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='selected_shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buttercheecksapp.useraddress'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_shipping_address', to='buttercheecksapp.useraddress'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_and_quantities',
            field=models.ManyToManyField(through='buttercheecksapp.SizeQuantity', to='buttercheecksapp.size'),
        ),
    ]
