# Generated by Django 4.2.4 on 2023-09-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0003_order_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
