# Generated by Django 4.2.4 on 2023-09-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0006_return'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
    ]
