# Generated by Django 4.2.4 on 2023-09-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0008_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
