# Generated by Django 4.2.4 on 2023-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0009_remove_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
