# Generated by Django 4.2.4 on 2023-09-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0011_product_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
