# Generated by Django 4.2.4 on 2023-09-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0013_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
