# Generated by Django 4.2.5 on 2023-09-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0014_order_estimated_delivery_time_order_shipping_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BABY_SWADDLES', 'Baby Swaddles'), ('BABY_ROMBERS', 'Baby Rombers'), ('BABY_JABLAS', 'Baby Jablas'), ('BABY_BLANKETS', 'Baby Blankets')], max_length=20, null=True),
        ),
    ]
