# Generated by Django 4.2.2 on 2023-11-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BABY_SWADDLES', 'Baby Swaddles'), ('BABY_ROMBERS', 'Baby Rombers'), ('BABY_JABLAS', 'Baby Jablas'), ('BABY_BLANKETS', 'Baby Blankets'), ('BABY_BEDDINGS', 'Baby Beddings'), ('MUSLIN_SWADDLES', 'Muslin Swaddles'), ('SNUG_SWADDLES', 'Snug Swaddles'), ('WRAP_SWADDLES', 'Wrap Swaddles'), ('MUSLIN_ROMBERS', 'Muslin Rombers'), ('MUSLIN_JABLAS', 'Muslin Jablas'), ('BURP_CLOTH SETS', 'Burp Cloth Sets'), ('BIB_CLOTH SETS', 'Bib Cloth Sets'), ('BABY_BED_SETS', 'Baby Bed Sets')], max_length=20, null=True),
        ),
    ]
