# Generated by Django 4.2.2 on 2023-11-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0019_alter_product_age_group_alter_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='shipping_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
