# Generated by Django 4.2.2 on 2023-12-06 05:54

import buttercheecksapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0022_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
    ]
