# Generated by Django 4.2.2 on 2023-12-06 05:55

import buttercheecksapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0023_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
    ]
