# Generated by Django 4.2.2 on 2023-12-27 05:27

import buttercheecksapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttercheecksapp', '0024_alter_product_image_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(null=True, upload_to='products/', validators=[buttercheecksapp.models.validate_image_size]),
        ),
    ]
